### ISSUE TITLE
Org members should be users

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/registry-spec#14]
One of the things we want at the product level is that org members be *users*, not *accounts*. There is of course the option to allow both, but it seems like that solution would be worse both from the registry perspective, and the product, so given the choice, we think users make more sense as members.

The most important consequence of this however, is that `register-org` can only be called when the origin has an associated user id in the registry. The reason being that the user registering the org should be added as the sole member, so that they can perform subsequent operations. It also means that transactions *on* orgs will be authenticated by users (who are members of the org).

There's a couple ways this can work:

**Explicit**
`register-org` takes a `user-id`, which the ledger verifies is associated with the tx origin. Same story for `unregister-org`, `register-member` etc. This effectively means the `account:user` relationship is `1:n`, and you can choose which user you want to authenticate as. This only requires a (merkleized) `UserId -> [AccountId]` index.

**Implicit**
`register-org` doesn't change, but the `account:user` relationship is `1:1`. This means that given an account id, I can lookup either exactly one associated user, or none (in the case I haven't registered a user id). This requires an index `AccountId -> Option<UserId>` which doesn't need to be merkleized, in addition to a merkleized `UserId -> AccountId` index.

I'm currently in favor of the *implicit* solution, because:
* It doesn't add an extra parameter to the transactions
* It uses less on-chain space (including a user id in txs takes up space)
* It simplifies the semantics a little bit by saying that you can't have an account control multiple user ids.

Thoughts? Other solutions?

@xla @radicle-dev/registry

**Comment by xla** [comment]
In favour of the `implicit` option as well for mostly the same reasons @cloudhead enumerated.

**Comment by NunoAlexandre** [comment]
>  It also means that transactions on orgs will be authenticated by users (who are members of the org).

So same thing as it is now, but by users instead of account, right? 

> Thoughts? Other solutions?

The `implicit` alternative is leaner. It suffices the requirements, doesn't break APIs, uses less chain space and it's also simpler, as you say.

The idea of an account controlling multiple users is interesting, though. Is there a place where I could read through the product thinking behind this design?

**Comment by cloudhead** [comment]
> So same thing as it is now, but by users instead of accounts, right?
>

Yeah, although there is a material difference there, since it's not just a matter of signature verification. This will have to happen inside the transaction runtime.
 
> 
> The idea of an account controlling multiple users is interesting, though. Is there a place where I could read through the product thinking behind this design?

This doesn't come from product actually, but if we choose this option we would have to think about its repercussions at the product level, and whether or not to expose it in the application.

**Comment by xla** [comment]
My strong intuition is that going with the `Implicit` approach will inform a simpler and easier to communicate product experience.

**Comment by kim** [comment]
A `1:n` `account:user` relationship does not actually make a lot of sense: anyone can engineer the reverse direction. Why else would I _pay_ for registering multiple users if not for anonymity?

So yeah, implicit :)

**Comment by cloudhead** [comment]
> A `1:n` `account:user` relationship does not actually make a lot of sense: anyone can engineer the reverse direction. Why else would I _pay_ for registering multiple users if not for anonymity?
> 
> So yeah, implicit :)

Lol, yeah good point.

Okay, I will go ahead and start spec'ing the implicit approach.

**Comment by geigerzaehler** [comment]
The implicit approach makes sense.

However, I would like to point out that we need to separate the concepts of key pairs and accounts more thoroughly. Key pairs are used for authentication via transaction signing. Accounts are balances associated with key pairs that control the account funds. For me it is not clear whether we want to associate an account with a user or just a key pair. This depends on whether a user holds a balance or whether an account holds a balance. 

A future use case to keep in mind is that we want to change the key pair that controls a user and potentially have multiple key pairs that do different things with a user.

**Comment by cloudhead** [comment]
Good point. I think for now we can keep it simple, and associate both users and accounts with a keypair. In the future, I would imagine that the account is associated with the user, and you can have any number of keypairs unlock the user.
