### ISSUE TITLE
Clarify user ID in org registration

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/registry-spec#18]
The spec says that the member list of an org is initialized with one user ID when an org is registered. We need to specify where this user ID comes from: It is the user ID that the author account is registered with. This also adds another validation. The author of the `register-org` transaction must be registered as a user.

**Comment by NunoAlexandre** [comment]
> The author of the register-org transaction must be registered as a user.

This part is already in the spec: "a is associated with a registered user u"

**Comment by geigerzaehler** [comment]
Yes, you’re right. Totally missed that.
